name: Build Docker Image
on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: ghcr.io/starlightautomation/autofeed-commander

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        env:
          DOCKER_IMAGE: ghcr.io/starlightautomation/autofeed-commander
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          file: docker/Dockerfile
          tags: ${{ steps.meta.outputs.tags }},ghcr.io/starlightautomation/autofeed-commander:latest
          labels: ${{ steps.meta.outputs.labels }}
